// Fetch All Users
export const FETCH_ALL_USERS_BEGIN = 'FETCH_ALL_USERS_BEGIN'
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS'
export const FETCH_ALL_USERS_ERROR = 'FETCH_ALL_USERS'

// Fetch Single Users
export const FETCH_SINGLE_USER_BEGIN = 'FETCH_SINGLE_USER_BEGIN'
export const FETCH_SINGLE_USER_SUCCESS = 'FETCH_SINGLE_USER_SUCCESS'
export const FETCH_SINGLE_USER_ERROR = 'FETCH_SINGLE_USER_ERROR'

// Create User
export const CREATE_SINGLE_USER_BEGIN = 'CREATE_SINGLE_USER_BEGIN'
export const CREATE_SINGLE_USER_SUCCESS = 'CREATE_SINGLE_USER_SUCCESS'
export const CREATE_SINGLE_USER_ERROR = 'CREATE_SINGLE_USER_ERROR'

// Update User
export const UPDATE_SINGLE_USER_BEGIN = 'UPDATE_SINGLE_USER_BEGIN'
export const UPDATE_SINGLE_USER_SUCCESS = 'UPDATE_SINGLE_USER_SUCCESS'
export const UPDATE_SINGLE_USER_ERROR = 'UPDATE_SINGLE_USER_ERROR'

// Delete User
export const DELETE_SINGLE_USER_BEGIN = 'DELETE_SINGLE_USER_BEGIN'
export const DELETE_SINGLE_USER_SUCCESS = 'DELETE_SINGLE_USER_SUCCESS'
export const DELETE_SINGLE_USER_ERROR = 'DELETE_SINGLE_USER_ERROR'
